config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'profiles#index'

  resources :profiles do 
    get :search, on: :collection
    post :rescan, on: :member
  end

  get "/:slug", to: "links#show", as: :link

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id          :bigint           not null, primary key
#  profile_id  :bigint           not null
#  url         :string           not null
#  slug        :string           not null
#  click_count :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Link < ApplicationRecord
  belongs_to :profile

  validates :url, presence: true, github_url: true
  validates :slug, presence: true, uniqueness: true

  def to_param
    slug
  end
  
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                      :bigint           not null, primary key
#  name                    :string           not null
#  gh_username             :string           not null
#  gh_name                 :string           not null
#  gh_followers            :string           not null
#  gh_following            :string           not null
#  gh_stars                :string           not null
#  gh_yearly_contributions :string           not null
#  gh_avatar_url           :string           not null
#  gh_organization         :string
#  gh_location             :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
class Profile < ApplicationRecord
  include PgSearch::Model

  has_one :link, dependent: :destroy
  
  pg_search_scope :search_all, against: [
    :name, 
    :gh_name,
    :gh_username,
    :gh_stars,
    :gh_followers,
    :gh_following,
    :gh_yearly_contributions,
    :gh_organization,
    :gh_location
  ], 
  using: { trigram: { word_similarity: true } },
  ignoring: :accents

  validates :name, presence: true
  validates :gh_name, presence: true
  validates :gh_stars, presence: true
  validates :gh_username, presence: true
  validates :gh_followers, presence: true
  validates :gh_following, presence: true
  validates :gh_avatar_url, presence: true
  validates :gh_yearly_contributions, presence: true
  validates :link, presence: true


  accepts_nested_attributes_for :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController 
  
  def show 
    @link = Link.find_by(slug: params[:slug])
    if @link.present?
      @link.increment!(:click_count)
      redirect_to @link.url, status: :moved_permanently
    else
      redirect_to root_path, alert: "Link não encontrado."
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController 
  before_action :set_profile, except: [:index, :new, :create, :search]

  def index 
    @profiles = Profile
      .includes(:link)
      .order(created_at: :desc)
  end

  def new
    @profile = ProfileBuilder.call
  end

  def edit; end;
  def show; end;

  def create 
    @profile = ProfileBuilder.call(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Perfil criado com sucesso.' }
      else
        flash.now.alert = "Perfil não pode ser criado."
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update 
    respond_to do |format|
      if ProfileUpdater.call(@profile, profile_params)
        format.html { redirect_to @profile, notice: 'Perfil atualizado com sucesso.' }
      else
        flash.now.alert = "Perfil não pode ser atualizado."
        format.html { render :edit, status: :unprocessable_entity }
      end  
    end
  end

  def destroy
    respond_to do |format|
      if @profile.destroy
        format.html { redirect_to profiles_path, notice: 'Perfil excluído com sucesso.' }
      else
        format.html { redirect_to profile_path(@profile), alert: "Perfil não pode ser excluído.", status: :unprocessable_entity }
      end
    end
  end

  def search 
    respond_to do |format|
      if params[:q].present?
        @profiles = Profile.includes(:link).search_all(params[:q])
        format.html { render :index }
        format.json { render json: @profiles }
      else        
        format.html do 
          @profiles = Profile.includes(:link).order(created_at: :desc)
          render :index
        end           
        format.json { render json: [] }
      end
    end
  end

  def rescan 
    gh_data = GithubUserScrapper.new(@profile.link.url).scrap 
    if @profile.update(gh_data)
      redirect_to @profile, notice: 'Perfil atualizado com sucesso.'
    else
      redirect_to @profile, alert: "Perfil não pode ser atualizado.", status: :unprocessable_entity
    end
  end


  private 

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params 
    params.require(:profile).permit(
      :name, 
      link_attributes: [:id, :url]
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title GhProfileIndexer
    meta content="width=device-width,initial-scale=1" name="viewport" 
    = csrf_meta_tags 
    = csp_meta_tag 
    
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' 
  body
    = render "shared/header"
    = render "shared/flashes"
    = yield 

app/views/profiles/_form.html.slim
.container 
  .form-card.profile-form-card
    .form-header
      span.text-bold = @profile.persisted? ? 'Editar perfil' : 'Novo perfil'
      = link_to "Voltar", profiles_path
    = form_with model: @profile, local: true do |f|
      .form-inputs
        = render "shared/form_errors", f: f
        .form-group
          = f.label :name
          = f.text_field :name, class: "text-input" 
          - if @profile.errors[:name]
            .text-error = @profile.errors[:name].join(', ')
        .form-group 
          = f.fields_for :link do |link_form|
            = link_form.label :url
            = link_form.text_field :url, class: "text-input"
            .text-error = @profile.link.errors[:url].join(', ')
      .form-actions
        = link_to "Cancelar", profiles_path            
        = f.submit "Salvar", class: "btn-primary"

app/views/profiles/_profile.html.slim
.profile-card-mini 
  .profile-main
    img.profile-img src=(profile.gh_avatar_url) width="150px"
    strong = profile.name 
  .profile-link
    = link_to link_url(profile.link), target: "_blank" do 
      bi.bi.bi-box-arrow-up-right.me-2
      span = link_url(profile.link)
  .profile-actions  
    a.btn-line-primary.btn-sm href=(edit_profile_path(profile)) 
      i.bi.bi-pencil.me-2
      span Editar
    a.btn-line-primary.btn-sm href=(profile_path(profile)) 
      i.bi.bi-eye.me-2
      span Visualizar

app/views/profiles/edit.html.slim
= render "form"

app/views/profiles/index.html.slim
.container 
  = form_with url: "/profiles/search", method: "get", html: { data: { controller: "search" }, class: "search-form" } do |f|
    .group
      = text_field_tag :q, params[:q], class: "text-input input-lg", placeholder: "Buscar", data: { "search-target": "input", action: "keyup->search#perform focus->search#perform"}, autocomplete: "off"
      button.btn-primary.btn-lg type="submit" name="search"
        i.bi.bi-search    
    .results-list.hidden data-search-target="list"
  - if @profiles.any?
    .profiles-list
      - @profiles.each do |profile|
        = render profile
  - else 
    .no-profile-card 
      .icon 
        i.bi.bi-emoji-frown
      .title Nenhum perfil encontrado 
      a.btn-primary href=(new_profile_path) 
        i.bi.bi-plus-circle.me-2
        span Novo perfil

app/views/profiles/new.html.slim
= render "form"

app/views/profiles/show.html.slim
.container 
  .profile-card-full
    .profile-header 
      strong = @profile.name
      = link_to "Voltar", profiles_path, class: "btn btn-link btn-sm "
    .profile-main 
      img.profile-img src=(@profile.gh_avatar_url) alt="Github profile avatar" width="250"
      .profile-name = @profile.gh_name
      .profile-username = @profile.gh_username
    .profile-stats
      .stat 
        i.bi.bi-people.text-muted 
        span = @profile.gh_followers
        span.text-muted followers
      .stat 
        i.bi.bi-dot
      .stat 
        span = @profile.gh_following
        span.text-muted following
      .stat 
        i.bi.bi-dot
      .stat 
        i.bi.bi-star.text-muted 
        span = @profile.gh_stars
    .profile-info
      - if @profile.gh_organization.present?
        .info
          i.bi.bi-building 
          span = @profile.gh_organization
      - if @profile.gh_location.present?
        .info
          i.bi.bi-geo-alt 
          span = @profile.gh_location
      .info
        i.bi.bi-git 
        span #{pluralize(@profile.gh_yearly_contributions.to_i, 'Contribuição', plural: 'Contribuições')} no último ano


    .profile-actions 
      a.btn-line-primary.btn-sm href=(rescan_profile_path(@profile)) data-method="post"
        i.bi.bi-arrow-clockwise
        span Re-escanear
      a.btn-line-primary.btn-sm href=(edit_profile_path(@profile)) 
        i.bi.bi-pencil
        span Editar            
      a.btn-line-error.btn-sm href=(profile_path(@profile)) data-confirm="Tem certeza que deseja excluir o perfil #{@profile.name}" data-method="delete"
        i.bi.bi-trash
        span Excluir

app/views/shared/_flashes.html.slim
- if notice 
  .container 
    .flash.notice
      span = notice
- if alert 
  .container 
    .flash.alert
      span = alert

app/views/shared/_form_errors.html.slim
- if f.object.errors.any?
  .form-errors
    .title Por favor corrija os erros abaixo 
    - f.object.errors.full_messages.each do |error_message| 
      .message = error_message 

app/views/shared/_header.html.slim
header.header 
  a.logo-link href=(root_path) 
    i.bi.bi-github.me-2
    span GitHub Profile Scrapper
  a.btn-primary href=(new_profile_path) 
    i.bi.bi-plus-circle.me-2
    span Novo perfil